pip install wheel so we have full tooling needed for installs
otherwise I observe:

    python -m pip install -q -r requirements-devel.txt
      ERROR: Command errored out with exit status 1:
       command: /home/appveyor/dlvenv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/appveyor/DLTMP/pip-install-d3o47b6c/jsmin/setup.py'"'"'; __file__='"'"'/home/appveyor/DLTMP/pip-install-d3o47b6c/jsmin/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /home/appveyor/DLTMP/pip-wheel-ttlau7j8
           cwd: /home/appveyor/DLTMP/pip-install-d3o47b6c/jsmin/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for jsmin
      ERROR: Command errored out with exit status 1:
       command: /home/appveyor/dlvenv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/appveyor/DLTMP/pip-install-d3o47b6c/python-xmp-toolkit/setup.py'"'"'; __file__='"'"'/home/appveyor/DLTMP/pip-install-d3o47b6c/python-xmp-toolkit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /home/appveyor/DLTMP/pip-wheel-tek2xcif
           cwd: /home/appveyor/DLTMP/pip-install-d3o47b6c/python-xmp-toolkit/
      Complete output (6 lines):
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for python-xmp-toolkit
    python -m pip install .
    Processing /home/appveyor/projects/datalad-container